routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('', 'PagesController@index')->name('pages.index');

Auth::routes();

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth', 'active']], function () {

    Route::get('', 'DashboardController@index')->name('dashboard.index');

    Route::patch('users/{id}/status', 'UsersController@status')->name('users.status');

    Route::patch('students/{id}/status', 'StudentsController@status')->name('students.status');

    Route::resource('users', 'UsersController', ['only' => ['index', 'create', 'store', 'edit', 'update', 'updatedata']]);

    //alterar senha
    Route::post('change-password', 'StudentsController@changePwd')->name('change.password');
    Route::get('change-password', 'StudentsController@pagePwd')->name('page.password');

    // Turma
    Route::resource('classes', 'ClassesController', ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']]);
    Route::get('my_classes', 'ClassesController@myIndex')->name('classes.mine.index');
    Route::resource('class_student', 'Class_StudentController', ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']]);
    Route::resource('class_lesson', 'Class_LessonController', ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']]);

    Route::get('/add_user/{id}', 'Class_StudentController@create')->name('add_user');
    Route::get('/add_lesson/{id}', 'Class_LessonController@create')->name('add_lesson');

    Route::get('/rem_student/{classe_id}/{student_id}', 'Class_StudentController@destroy')->name('rem_student');
    Route::get('/rem_lesson/{classe_id}/{lesson_id}', 'Class_LessonController@destroy')->name('rem_lesson');

    Route::get('/classes/{id}/close', 'ClassesController@close')->name('close_classe');

    Route::resource('lessons', 'LessonsController', ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']]);

    Route::get('my_lessons', 'LessonsController@myIndex')->name('lessons.mine.index');

    Route::get('lesson/results/{lessonid}', 'ResultsController@lesson')->name('lesson.results');
    Route::get('lesson/results/{lessonid}/student/{studentid}', 'ResultsController@student')->name('lesson.results.student');
    Route::get('lesson/results/{lessonid}/student/{studentid}/download/lastframes', 'ResultsController@lastFrames')->name('lesson.results.student.download.lastFrames');
    Route::get('lesson/results/{lessonid}/student/{studentid}/download/lastframesxml', 'ResultsController@lastFramesXml')->name('lesson.results.student.download.lastFramesXml');



    Route::resource('evaluation_results', 'EvaluationsController', ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']]);

    Route::get('lesson/results/evaluation/index/lesson/{lessonid}/student/{studentid}', 'EvaluationsController@route')->name('lesson.results.evaluation_results.route');

    Route::get('lesson/results/evaluation/create/{lessonid}/student/{studentid}', 'EvaluationsController@create')->name('lesson.results.evaluation_results.create');
    Route::get('lesson/results/evaluation/edit/{lessonid}/student/{studentid}', 'EvaluationsController@edit')->name('lesson.results.evaluation_results.edit');


    Route::get('impression/{id}', 'ImpressionsController@show')->name('impressions.show');


    Route::resource('student', 'StudentsController', ['only' => ['index', 'create', 'store', 'edit', 'update']]);

    Route::group(['prefix' => 'graphics'], function () {
        Route::get('student', 'GraphicsController@index_student')->name('graphics_of_student');
        Route::get('user', 'GraphicsController@index_user')->name('graphics_of_user');

    });


    Route::group(['prefix' => 'statistic'], function () {
        Route::get('user', 'StatisticsModuleController@index')->name('statistic_module');

    });



    Route::get('graphics/index','GraphicsController@index')->name('graphics.index');

    Route::post('graphics/index','GraphicsController@plot_Student')->name('plot.student');

    Route::get('graphics/plotEmotionOfStudentByLesson/{lessonId}/{studentId}','GraphicsController@plotVariationOfStudentEmotionByLesson')->name('plot.student.lesson');
    Route::get('graphics/plotAverageOfEmotionsByStudent/{studentId}','GraphicsController@plotAverageOfEmotionsByStudent')->name('plot.average.student');
    Route::get('graphics/plotAverageOfEmotionsByLesson/{lessonId}','GraphicsController@plotAverageOfEmotionsByLesson')->name('plot.average.lesson');
    Route::get('graphics/plotAverageOfEmotionsByClass/{classId}','GraphicsController@plotAverageOfEmotionsByClass')->name('plot.average.class');

    Route::get('graphics/plotHitRateByStudent/{studentId}','GraphicsController@plotHitRateByStudent')->name('plot.hitRate.student');
    Route::get('graphics/plotHitRateByLesson/{lessonId}','GraphicsController@plotHitRateByLesson')->name('plot.hitRate.lesson');
    Route::get('graphics/plotHitRateByClass/{classId}','GraphicsController@plotHitRateByClass')->name('plot.hitRate.class');

    //webServer
    Route::get('graphics/filtered/{student_id}','GraphicsController@student_lessons');
    Route::get('statistic/filtered/{student_id}','GraphicsController@student_lessons');


    Route::get('statistic/emotion/{emotion}','StatisticsModuleController@maior_e_menor_indice_emocao');
    Route::get('statistic/lesson/{lesson}/emotion/{emotion}','StatisticsModuleController@maior_e_menor_indice_aluno_emocao');
    Route::get('statistic/student/{student_id}','StatisticsModuleController@individual_aluno');
    Route::get('statistic/lesson/{lesson_id}','StatisticsModuleController@individual_aula');
    Route::get('statistic/report/lesson/{lesson_id}','StatisticsModuleController@relatorio_resultados_aula');
    Route::get('statistic/emotion_lesson/student/{student_id}','StatisticsModuleController@maior_menor_indice_aula_emocao_aluno');
    Route::get('statistic/evaluation/student/{student_id}/lesson/{lesson_id}','StatisticsModuleController@results_evaluation');

});

Route::get('setlocale/{locale}', function ($locale) {
    if (in_array($locale, \Config::get('app.locales'))) {
        Session::put('locale', $locale);
    }
    return redirect()->back();
})->name('setlocale');


Route::get('ils', 'IlsController@index');

Route::resource('tests', 'TestsController', ['only' => ['show', 'store']]);

Route::get('lesson/{slug}', 'LessonsController@show');

Route::post('students/email', 'StudentsController@store')->name('students.email');

Route::post('students/add', 'StudentsController@secStore')->name('students.register.email');

Route::get('student/register', function () {
    return view('student.create');
})->name('student.register');


Route::put('student/{uuid}', 'StudentRegistrationController@update');

Route::post('student/ils/{uuid}', 'StudentsIlsController@store');

Route::post('studentsresults', 'StudentsResultsController@store');

Route::get('api/lessons', 'PublicLessonsController@index');

Route::get('api/lessons/all', 'PublicLessonsController@indexAll');

Route::get('lessons', 'PublicLessonsController@view')->name('lessons');

Route::get('lessons/all', 'PublicLessonsController@viewAll')->name('lessons.all');

Route::post('impressions', 'ImpressionsController@store');

Route::get('ontoafter/lesson/{lessonid}/student/{studentid}/download/lastframesxml', 'ResultsController@lastFramesXmlAfterLesson')->name('lesson.results.student.download.lastFramesXmlAfter');


Route::resource('accessibility', 'AccessibilityController', ['only' => ['index']]);

Route::resource('map', 'MapController', ['only' => ['index']]);

//Route::get('onto', 'GenerateUsersFromStudentsController@generate')->name('onto');

// fase II
//Route::get('onto/{uuid}', 'XmlExportationController@storeStudentIdIntoOnto');
//
//Route::get('testing/', 'StudentRegistrationController@testAcademic');

app/Http/Controllers/Class_StudentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreClass_StudentRequest;

use App\Models\Classe;
use App\Models\ClasseStudent;
use App\Models\Student;

use App\Policies\TaskPolicy;
use Illuminate\Support\Facades\Auth;


/**
 * Class ClassesController
 * @package App\Http\Controllers
 */
class Class_StudentController extends Controller
{


    public function create($id)
    {
        if (Auth::check()) {
            if (Auth::user()->isAdmin() || Auth::user()->isCollaborator()) {
                $students = Student::all();
                $std = Classe::find($id)->students()->orderBy('name')->paginate(5);

                foreach ($std as $st) {
                    $students = $students->except($st->id);
                }


                $class = $this->getEditedClass($id);

                return view('class_student.add', compact('students', 'class', 'std'));
            }
        }
    }


    public function destroy($classe_id, $student_id)
    {
        $classes = ClasseStudent::where('classe_id', '=', $classe_id);
        $classe_student = $classes->where('student_id', '=', $student_id);

        $classe_student->delete();

        return redirect()->route('classes.edit', [$classe_id])->with('status', trans('status.class_student.deleted'));
    }


    public function store(StoreClass_StudentRequest $request)
    {

        $data = $request->only([

            'classe_id',
            'student_id'

        ]);


        ClasseStudent::createNew($data);

        return redirect()->route('add_user', ['id' => $data['classe_id']])->with('status', trans('status.class_student.add'));

    }


    private function getEditedClass($id)
    {

        $class = Classe::findOrFail($id);
        return $class;

    }
}

resources/views/class_student/add.blade.php
@extends('layouts.app')

@section('heading', $class->name)

@section('content')

    <button type="button" name="id_class" class="btn btn-primary btn-block" data-toggle="modal" data-target="#ilsModal">
        @lang('strings.add_students')
    </button>

    <form id="student">

        {{--Estudantes--}}
        <label><h3>@lang('strings.students')</h3></label>

        @if(! $std->isEmpty())
            <div class="table-responsive">

                <table class="table">

                    <thead>
                    <tr>
                        <th>@lang('strings.name')</th>
                    </tr>
                    </thead>

                    <tbody>


                    @foreach($std as $st)
                        <tr>
                            <td>{{ $st->name }}</td>

                        </tr>
                    @endforeach
                    </tbody>

                </table>
                <a href="{{route('classes.index')}}" class="btn btn-block btn-default"> @lang('strings.back')</a>
            </div>

            {{ $std->links() }}

        @else

            <div class="alert alert-warning">@lang('status.class_student.none')</div>

        @endif

    </form>


    <form method="POST" action="{{ route('class_student.store') }}" class="form" id="framework_form">


        {{ csrf_field() }}


        <div class="modal fade" id="ilsModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">

            <div class="modal-dialog" role="document">

                <div class="modal-content">




                    {{--pega o id da turma--}}
                    <div class="form-group">
                        <input style="display: none" name="classe_id" type="text" class="form-control"
                               value="{{ $class->id }}" readonly>
                    </div>


                    <div class="modal-body" align="center">
                        <label style="text-align: center">@lang('strings.students')</label>
                        <br>

                        <div class="form-group">
                            <select id="framework" name="student_id[]" multiple class="form-control select2"
                                    style="width: 100%" required>
                                @if(! $students->isEmpty())
                                    @foreach($students as $student)
                                        <option value="{{ $student->id }}">
                                            {{ $student->name }}
                                        </option>
                                    @endforeach
                                @else
                                    <div class="alert alert-warning">@lang('status.class_student.none')</div>
                                @endif
                            </select>
                        </div>

                    </div>

                    <input type="submit" value="@lang('strings.save')" class="btn btn-block btn-success">

                    <div class="modal-footer">
                        <button type="button" class="btn btn-default"
                                data-dismiss="modal">@lang('strings.close')</button>
                    </div>

                </div>

            </div>

        </div>

    </form>

@endsection